services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drug-allergy-api
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: drug-allergy-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
